-- =====================================================================
-- db-scheduler 分布式任务调度核心表 (Oracle 数据库方言 DDL)
-- 用于 Oracle 11g / 12c / 19c / 21c 生产环境适配
-- =====================================================================

-- 方案一：标准 Oracle 生产表结构（推荐，支持 BLOB 二进制任务上下文与高精度时区时间戳）
CREATE TABLE "SCHEDULED_TASKS" (
    "TASK_NAME" VARCHAR2(255) NOT NULL,
    "TASK_INSTANCE" VARCHAR2(255) NOT NULL,
    "TASK_DATA" BLOB,
    "EXECUTION_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "PICKED" NUMBER(1,0) DEFAULT 0 NOT NULL,
    "PICKED_BY" VARCHAR2(255),
    "LAST_SUCCESS" TIMESTAMP(6) WITH TIME ZONE,
    "LAST_FAILURE" TIMESTAMP(6) WITH TIME ZONE,
    "CONSECUTIVE_FAILURES" NUMBER(11,0) DEFAULT 0,
    "LAST_HEARTBEAT" TIMESTAMP(6) WITH TIME ZONE,
    "VERSION" NUMBER(20,0) DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_SCHEDULED_TASKS" PRIMARY KEY ("TASK_NAME", "TASK_INSTANCE")
);

CREATE INDEX "IDX_SCHED_EXEC_TIME" ON "SCHEDULED_TASKS" ("EXECUTION_TIME");
CREATE INDEX "IDX_SCHED_LAST_HEARTBEAT" ON "SCHEDULED_TASKS" ("LAST_HEARTBEAT");

-- 方案二：简易兼容版表结构（使用 DATE / VARCHAR2(2000)）
-- 如果环境不使用 BLOB 或特定序列化器，可使用如下 DDL：
/*
CREATE TABLE "SCHEDULED_TASKS" (
    "TASK_NAME" VARCHAR2(255) NOT NULL ENABLE, 
    "TASK_INSTANCE" VARCHAR2(255) NOT NULL ENABLE, 
    "EXECUTION_TIME" DATE NOT NULL ENABLE, 
    "PICKED" NUMBER(4,0) NOT NULL ENABLE, 
    "PICKED_BY" VARCHAR2(255), 
    "LAST_SUCCESS" DATE, 
    "LAST_FAILURE" DATE, 
    "CONSECUTIVE_FAILURES" NUMBER(11,0), 
    "LAST_HEARTBEAT" DATE, 
    "VERSION" NUMBER(20,0) NOT NULL ENABLE, 
    "TASK_DATA" VARCHAR2(2000),
    CONSTRAINT "PK_SCHEDULED_TASKS_COMPAT" PRIMARY KEY ("TASK_NAME", "TASK_INSTANCE")
);

CREATE INDEX "IDX_SCHED_EXEC_DATE" ON "SCHEDULED_TASKS" ("EXECUTION_TIME");
CREATE INDEX "IDX_SCHED_LAST_HB_DATE" ON "SCHEDULED_TASKS" ("LAST_HEARTBEAT");
*/
